name: fib-calc
on:
  push:
    branches:
      - main 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t sidsipani23/fib-calc-client -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true sidsipani23/fib-calc-client npm test
 
      - run: docker build -t sidsipani23/fib-calc-client ./client
      - run: docker build -t sidsipani23/fib-calc-nginx ./nginx
      - run: docker build -t sidsipani23/fib-calc-server ./server
      - run: docker build -t sidsipani23/fib-calc-worker ./worker
 
      - run: docker push sidsipani23/fib-calc-client
      - run: docker push sidsipani23/fib-calc-nginx
      - run: docker push sidsipani23/fib-calc-server
      - run: docker push sidsipani23/fib-calc-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fib-calc
          environment_name: fib-calc-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-826754917540
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip